language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t hryhorii/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hryhorii/docker-react npm test  

after_success:
  - docker build -t hryhorii/multi-client ./client
  - docker build -t hryhorii/multi-nginx ./nginx
  - docker build -t hryhorii/multi-server ./server
  - docker build -t hryhorii/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push hryhorii/multi-client
  - docker push hryhorii/multi-nginx
  - docker push hryhorii/multi-server
  - docker push hryhorii/multi-worker